NAME: '.starnet'

DATASET:
  TYPE: 'pedes'
  NAME: 'PETA'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: True
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 128

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  TYPE: 'starnet_s3' 

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  MAX_EPOCH: 30
  BATCH_SIZE: 64
  OPTIMIZER:
    TYPE: 'adamw'
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_STEP: [10, 15]
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
