NAME: '.tiny_vit_21m'

DATASET:
  TYPE: 'pedes'
  NAME: 'PA100k'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 128

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  TYPE: 'tiny_vit_21m'

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 64
  OPTIMIZER:
    TYPE: 'adamw'
    WEIGHT_DECAY: 0.0
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
